version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_DATABASE=farmsoftware
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local
